---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    run: {{ template "application.fullname" . }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "application.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{.Values.ingress.scheme}}
    {{ if .Values.ingress.dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{.Values.ingress.dns.name}}
    {{ end }}
    {{ if .Values.ingress.https.enabled }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type":"redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: {{.Values.ingress.https.certificateArn}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    {{ end }}
  labels:
    app: {{ template "application.fullname" . }}-ingress
spec:
  rules:
  - http:
      paths:
      {{ if .Values.ingress.https.enabled }}
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        path: /*
    {{ end }}
      - backend:
          serviceName: {{ template "application.fullname" . }}-service
          servicePort: 80
        path: /*

